Ecomproject/Ecomapp/urls.py
from django.urls import path,include

from Ecomapp import views
app_name='Ecomapp'
urlpatterns = [

    path('',views.AllProdCat,name='AllProdCat'),
    path('<slug:c_slug>/',views.AllProdCat,name='products_by_cat'),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProdDetail,name='ProdDetails'),
]

Ecomproject/Ecomproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include


from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('Ecomapp.urls')),
    path('search/',include('searchapp.urls')),
    # path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Ecomproject/searchapp/urls.py
from django.urls import path

from . import views
app_name = 'searchapp'

urlpatterns = [

    path('',views.Searches,name='searchresult'),

]

Ecomproject/Ecomapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    desc = models.TextField()
    image = models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('Ecomapp:products_by_cat',args=[self.slug])

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    desc = models.TextField()
    image = models.ImageField(upload_to='product',blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('Ecomapp:ProdDetails',args=[self.category.slug,self.slug])

    def __str__(self):
        return self.name

Ecomproject/searchapp/models.py
from django.db import models

# Create your models here.

Ecomproject/Ecomapp/views.py
from django.shortcuts import render, get_object_or_404
from . models import Category,Product

# Create your views here.
def demo(request):
    return render(request,'hello.html')

def AllProdCat(request,c_slug=None):
    products = None
    c_page = None
    if c_slug != None:
        c_page = get_object_or_404(Category,slug=c_slug)
        products = Product.objects.all().filter(category=c_page,available=True)
    else:
        products = Product.objects.all().filter(available=True)
    return render(request,'category.html',{'category':c_page,'products':products})

def ProdDetail(request,c_slug,product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

Ecomproject/searchapp/views.py
from django.db.models import Q
from django.shortcuts import render
from Ecomapp.models import Product

# Create your views here.
def Searches(request):
    query = None
    products = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__icontains=query) | Q(desc__icontains=query))
    return render(request, 'search.html', {'query': query, 'products': products})

Ecomproject/Ecomapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
{% include 'footer.html' %}
</body>
</html>

Ecomproject/Ecomapp/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if category %}
    {{category.description}}
{% else %}
    Welcome to Ecommerce App
{% endif %}

{% endblock %}

{% block title %}
{% if category %}
    {{category.name}}
{% else %}
    Our Category
{% endif %}
{% endblock %}

{% block content %}
{% if category %}
    <div>
        <div>
<!--            <p><a href="{% url 'Ecomapp:AllProdCat' %}">our products11 </a>"</p>-->
        </div>
    </div>
{% endif %}

<div>
    {% if category %}
        <img src="{{category.image.url}}" alt="{{category.name}}" style="width:100%;height:370px;">
</div>

<br>

<div>
    <h2>{{category.name}}</h2><br>
    <p>{{category.desc}}</p>

</div>
    {% else %}
<div>
    <img src="{% static 'img/banner.jpg'  %}" alt="our products" style="width:100%;height:350px;">
</div><br>
<div>
    <h2 style="text-align:center;">our products</h2>
    <p>E-commerce, or electronic commerce, refers to the buying and selling of
        goods and services over the internet. It encompasses a wide range of online
        business activities, from retail shopping to auctioning and payment services.
        Here's a detailed overview </p>

</div>
{% endif %}
<div>
    <div class="container">
        <div class="row">
            {% for product in products %}
            <div class="col-md-4">

                <div>
                    <div>
                        <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}"></a>
                        <div>
                            <h2>{{product.name }}</h2>
                            <p>{{product.price}}</p>
                            <p>{{product.desc}}</p>
                        </div>
                    </div>
                </div>

            </div>
            {% endfor %}
            </div>
        </div>

</div>
{% endblock %}

Ecomproject/Ecomapp/templates/footer.html
<p style="text-align:center;">&copy; right reserved</p>

Ecomproject/Ecomapp/templates/header.html
{% load static %}

<header>
  <center>
    <a href="{% url 'Ecomapp:AllProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="logimage" style="width:150px;"></a>
  </center>
</header>

Ecomproject/Ecomapp/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>hello</h1>
</body>
</html>

Ecomproject/Ecomapp/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</head>



<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'Ecomapp:AllProdCat' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">


        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'Ecomapp:AllProdCat' %}">All Products</a></li>
            {% for cat in links %}

            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>

            {% endfor %}

          </ul>
        </li>
<!--        <li class="nav-item">-->
<!--          <a class="nav-link disabled" aria-disabled="true">Disabled</a>-->
<!--        </li>-->
      </ul>
      <form class="d-flex" role="search" action="{% url 'searchapp:searchresult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>



<!--<nav>-->
<!--  <ul>-->
<!--    <li><a href="{% url 'Ecomapp:AllProdCat' %}">All Products1</a> </li>-->
<!--    {% for cat in links %}-->
<!--    <li><a href="{{cat.get_url}}">{{cat.name}}</a></li>-->
<!--    {% endfor %}-->
<!--  </ul>-->
<!--</nav>-->

Ecomproject/Ecomapp/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!--<div>-->
<!--    <a href="{% url 'Ecomapp:AllProdCat' %}">All Products</a> <br>-->
<!--    <a href="{{ product.category.get_url}}">{{product.category}}</a>-->
<!--</div>-->
<div>
    <div>
        <img src="{{product.image.url}}" alt="{{product.name}}">
    </div>
</div>
<div>
    <h2>{{product.name}}</h2>
    <p>${{product.price}}</p>
    <p>{{product.desc}}</p>
    {% if product.stock <= 0 %}
    <p><b>Out of Stock</b></p>
    {% else %}

    {% endif %}
</div>

{% endblock %}

Ecomproject/Ecomapp/templates/search.html
{% extends 'base.html' %}

{% block content %}

{% if query %}
<div class="container">
  <p><b>You Searched for {{query}}</b></p>
     {% for product in products %}
        <div>
            <div>
                <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div>
                    <h2>{{product.name }}</h2>
                    <p>{{product.price}}</p>
                    <p>{{product.desc}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
</div>

{% else %}
<div class="container">
  <P text-center><b>{{query}}: No results</b></P>
</div>
{% endif %}



{% endblock %}